//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SheepLoopsAdministrador.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class producto
    {
        public int codigoproducto { get; set; }
        public string nombreproducto { get; set; }
        public string imagenproducto { get; set; }
        public string descripcionproducto { get; set; }
        public decimal precioproducto { get; set; }
        public int cantidadproducto { get; set; }
        public bool activoproducto { get; set; }
    }
}
